# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 400)
        MainWindow.setMinimumSize(QtCore.QSize(800, 400))
        MainWindow.setMaximumSize(QtCore.QSize(800, 400))
        MainWindow.setStyleSheet("background-color: rgb(204, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.question = QtWidgets.QLabel(self.centralwidget)
        self.question.setGeometry(QtCore.QRect(50, 30, 700, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI Light")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.question.setFont(font)
        self.question.setObjectName("question")
        self.next = QtWidgets.QPushButton(self.centralwidget)
        self.next.setEnabled(False)
        self.next.setGeometry(QtCore.QRect(50, 320, 55, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI Light")
        font.setPointSize(9)
        self.next.setFont(font)
        self.next.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.next.setFlat(True)
        self.next.setObjectName("next")
        self.ask1 = QtWidgets.QRadioButton(self.centralwidget)
        self.ask1.setGeometry(QtCore.QRect(50, 100, 700, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI Light")
        font.setPointSize(10)
        self.ask1.setFont(font)
        self.ask1.setObjectName("ask1")
        self.ask2 = QtWidgets.QRadioButton(self.centralwidget)
        self.ask2.setGeometry(QtCore.QRect(50, 140, 700, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI Light")
        font.setPointSize(10)
        self.ask2.setFont(font)
        self.ask2.setObjectName("ask2")
        self.ask4 = QtWidgets.QRadioButton(self.centralwidget)
        self.ask4.setEnabled(False)
        self.ask4.setGeometry(QtCore.QRect(50, 220, 700, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI Light")
        font.setPointSize(10)
        self.ask4.setFont(font)
        self.ask4.setObjectName("ask4")
        self.ask3 = QtWidgets.QRadioButton(self.centralwidget)
        self.ask3.setEnabled(False)
        self.ask3.setGeometry(QtCore.QRect(50, 180, 700, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI Light")
        font.setPointSize(10)
        self.ask3.setFont(font)
        self.ask3.setObjectName("ask3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Определение курильщика"))
        self.question.setText(_translate("MainWindow", "1/12    Каков ваш пол?"))
        self.next.setText(_translate("MainWindow", "Далее"))
        self.ask1.setText(_translate("MainWindow", "Мужской"))
        self.ask2.setText(_translate("MainWindow", "Женский"))
        self.ask4.setText(_translate("MainWindow", "Женский"))
        self.ask3.setText(_translate("MainWindow", "Мужской"))
